//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holger_hals_betvinger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Holger_hals_betvinger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=13,y=9:(3);x=13,y=10:(3);x=13,y=11:(3);x=13,y=12:(3);x=13,y=13:(3);x=13,y=14:(3);x=13,y=15:(3);x=13,y=16:(3);x=14,y=16:(3);x=15,y=16:(3);x=16,y=16:(3);x=17,y=16:(3);x=18,y=16:(3);x=19,y=16:(3);x=13,y=8:(3);x=14,y=8:(3);x=15,y=8:(3);x=16,y=8:(3);x=17,y=8:(3);x=18,y=8:(3);x=19,y=8:(3);x=20,y=8:(3);x=20,y=9:(3);x=20,y=10:(3);x=20,y=11:(3);x=20,y=12:(3);x=20,y=13:(3);x=20,y=14:(3);x=20,y=15:(3);x=20,y=16:(3);x=20,y=17:(2);x=20,y=18:(2);x=20,y=19:(2);x=20,y=20:(2);x=20,y=21:(2);x=20,y=22:(2);x=20,y=23:( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ALotOfButtons {
            get {
                return ResourceManager.GetString("ALotOfButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=11,y=9:(3);x=5,y=17:(3);x=6,y=17:(3);x=7,y=17:(3);x=8,y=17:(3);x=9,y=17:(3);x=10,y=17:(3);x=11,y=17:(3);x=12,y=17:(3);x=13,y=17:(3);x=14,y=17:(3);x=15,y=17:(3);x=16,y=17:(3);x=17,y=17:(3);x=18,y=17:(3);x=5,y=18:(2);x=5,y=19:(2);x=6,y=19:(2);x=7,y=19:(2);x=8,y=19:(2);x=9,y=19:(2);x=10,y=19:(2);x=11,y=19:(2);x=12,y=19:(2);x=13,y=19:(2);x=14,y=19:(2);x=15,y=19:(2);x=16,y=19:(2);x=17,y=19:(2);x=18,y=19:(2);x=19,y=19:(2);x=19,y=18:(2);x=18,y=18:(2);x=17,y=18:(2);x=16,y=18:(2);x=15,y=18:(2);x=14,y=18:(2) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arrows {
            get {
                return ResourceManager.GetString("Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=7,y=11:(3);x=8,y=11:(3);x=9,y=11:(3);x=10,y=11:(3);x=12,y=11:(3);x=13,y=11:(3);x=14,y=11:(3);x=15,y=11:(3);x=16,y=11:(3);x=17,y=11:(3);x=17,y=12:(3);x=7,y=12:(3);x=7,y=13:(3);x=7,y=14:(3);x=7,y=15:(3);x=7,y=16:(3);x=17,y=13:(2);x=16,y=12:(2);x=15,y=12:(2);x=13,y=12:(2);x=12,y=12:(2);x=11,y=12:(2);x=10,y=12:(2);x=9,y=12:(2);x=17,y=17:(3);x=7,y=17:(3);x=7,y=18:(3);x=8,y=18:(3);x=9,y=18:(3);x=10,y=18:(3);x=11,y=18:(3);x=12,y=18:(3);x=13,y=18:(3);x=14,y=18:(3);x=15,y=18:(3);x=16,y=18:(3);x=17,y=18:(3); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigButtonLevel {
            get {
                return ResourceManager.GetString("BigButtonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=1,y=0:(3);x=2,y=0:(3);x=3,y=0:(3);x=4,y=0:(3);x=5,y=0:(3);x=6,y=0:(3);x=7,y=0:(3);x=8,y=0:(3);x=9,y=0:(3);x=11,y=0:(3);x=12,y=0:(3);x=13,y=0:(3);x=18,y=0:(3);x=19,y=0:(3);x=20,y=0:(3);x=21,y=0:(3);x=22,y=0:(3);x=23,y=0:(3);x=24,y=0:(3);x=25,y=0:(3);x=26,y=0:(3);x=27,y=0:(3);x=28,y=0:(3);x=29,y=0:(3);x=30,y=0:(3);x=10,y=0:(3);x=31,y=0:(3);x=1,y=2:(1);x=2,y=2:(1);x=3,y=2:(1);x=5,y=2:(1);x=6,y=2:(1);x=7,y=2:(1);x=8,y=2:(1);x=9,y=2:(1);x=10,y=2:(1);x=11,y=2:(1);x=12,y=2:(1);x=19,y=2:(1);x=20,y=2:(1);x= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigDoorRoom {
            get {
                return ResourceManager.GetString("BigDoorRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=8,y=11:(3);x=9,y=11:(3);x=12,y=11:(3);x=13,y=11:(3);x=14,y=11:(3);x=15,y=11:(3);x=16,y=11:(3);x=19,y=11:(3);x=20,y=11:(3);x=20,y=12:(3);x=20,y=13:(3);x=20,y=14:(3);x=20,y=15:(3);x=20,y=16:(3);x=8,y=12:(3);x=8,y=13:(3);x=8,y=14:(3);x=8,y=15:(3);x=8,y=16:(3);x=8,y=17:(3);x=8,y=18:(3);x=9,y=18:(3);x=10,y=18:(3);x=11,y=18:(3);x=12,y=18:(3);x=17,y=18:(3);x=18,y=18:(3);x=19,y=18:(3);x=20,y=18:(3);x=20,y=17:(3);x=12,y=19:(3);x=12,y=20:(3);x=12,y=21:(3);x=12,y=22:(3);x=13,y=22:(3);x=14,y=22:(3);x=15,y=22:( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DoubleDoorDoublePlates {
            get {
                return ResourceManager.GetString("DoubleDoorDoublePlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=14,y=14:(5);x=14,y=15:(5);x=15,y=15:(5);x=15,y=14:(5);x=13,y=13:(4);x=16,y=17:(4);x=15,y=17:(4);x=14,y=17:(4);x=8,y=13:(4);x=7,y=13:(4);x=6,y=13:(4);x=5,y=13:(4);x=12,y=17:(4);x=11,y=17:(4);x=10,y=17:(4);x=5,y=17:(4);x=9,y=13:(4);x=9,y=14:(4);x=9,y=15:(4);x=9,y=16:(4);x=5,y=14:(4);x=5,y=15:(4);x=5,y=16:(4);x=18,y=13:(4);x=19,y=13:(4);x=20,y=13:(4);x=21,y=13:(4);x=25,y=13:(4);x=25,y=14:(4);x=25,y=15:(4);x=25,y=16:(4);x=25,y=17:(4);x=5,y=18:(4);x=5,y=19:(4);x=5,y=20:(4);x=5,y=21:(4);x=6,y=21:(4);x=7, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyMaze {
            get {
                return ResourceManager.GetString("EasyMaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=6,y=5:(3);x=7,y=5:(3);x=8,y=5:(3);x=9,y=5:(3);x=10,y=5:(3);x=11,y=5:(3);x=12,y=5:(3);x=13,y=5:(3);x=14,y=5:(3);x=15,y=5:(3);x=16,y=5:(3);x=17,y=5:(3);x=18,y=5:(3);x=19,y=5:(3);x=20,y=5:(3);x=21,y=5:(3);x=22,y=5:(3);x=23,y=5:(3);x=6,y=6:(3);x=6,y=7:(3);x=6,y=8:(3);x=6,y=9:(3);x=6,y=11:(3);x=6,y=12:(3);x=6,y=13:(3);x=6,y=14:(3);x=6,y=15:(3);x=6,y=16:(3);x=6,y=10:(3);x=7,y=16:(3);x=8,y=16:(3);x=9,y=16:(3);x=10,y=16:(3);x=11,y=16:(3);x=15,y=16:(3);x=16,y=16:(3);x=17,y=16:(3);x=18,y=16:(3);x=19,y=16:(3) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=10:(3);x=11,y=10:(3);x=13,y=10:(3);x=15,y=10:(3);x=17,y=10:(3);x=18,y=11:(3);x=18,y=13:(3);x=18,y=15:(3);x=18,y=17:(3);x=8,y=11:(3);x=8,y=13:(3);x=8,y=15:(3);x=8,y=17:(3);x=9,y=18:(3);x=11,y=18:(3);x=13,y=18:(3);x=15,y=18:(3);x=17,y=18:(3);x=8,y=19:(2);x=9,y=19:(2);x=10,y=19:(2);x=11,y=19:(2);x=12,y=19:(2);x=13,y=19:(2);x=14,y=19:(2);x=15,y=19:(2);x=16,y=19:(2);x=17,y=19:(2);x=18,y=19:(2);x=17,y=11:(2);x=15,y=11:(2);x=14,y=11:(2);x=11,y=11:(2);x=9,y=11:(2);x=8,y=10:(9);x=10,y=10:(9);x=12,y=10:( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstPuzzle {
            get {
                return ResourceManager.GetString("FirstPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=13,y=20:(3);x=13,y=19:(3);x=13,y=18:(3);x=13,y=17:(3);x=13,y=16:(3);x=13,y=15:(3);x=13,y=14:(3);x=13,y=13:(3);x=13,y=12:(3);x=13,y=11:(3);x=11,y=8:(3);x=12,y=8:(3);x=13,y=8:(3);x=12,y=11:(3);x=11,y=11:(3);x=10,y=11:(3);x=10,y=10:(3);x=10,y=9:(3);x=10,y=8:(3);x=13,y=7:(3);x=15,y=7:(3);x=15,y=8:(3);x=15,y=9:(3);x=15,y=10:(3);x=15,y=11:(3);x=15,y=12:(3);x=15,y=13:(3);x=15,y=14:(3);x=15,y=15:(3);x=15,y=16:(3);x=15,y=17:(3);x=15,y=18:(3);x=15,y=19:(3);x=15,y=20:(3);x=14,y=20:(3);x=15,y=21:(2);x=15,y=22: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstStone {
            get {
                return ResourceManager.GetString("FirstStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=7:(3);x=9,y=8:(3);x=9,y=9:(3);x=9,y=10:(3);x=9,y=11:(3);x=9,y=12:(3);x=9,y=14:(3);x=9,y=13:(3);x=9,y=15:(3);x=9,y=16:(3);x=9,y=17:(3);x=9,y=20:(3);x=10,y=20:(3);x=11,y=20:(3);x=12,y=20:(3);x=13,y=20:(3);x=14,y=20:(3);x=15,y=20:(3);x=16,y=20:(3);x=17,y=20:(3);x=18,y=20:(3);x=19,y=20:(3);x=20,y=20:(3);x=21,y=20:(3);x=21,y=19:(3);x=21,y=18:(3);x=21,y=17:(3);x=21,y=16:(3);x=21,y=15:(3);x=21,y=14:(3);x=21,y=12:(3);x=21,y=11:(3);x=21,y=10:(3);x=21,y=9:(3);x=21,y=8:(3);x=21,y=7:(3);x=21,y=6:(3);x=20,y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstTwoStone {
            get {
                return ResourceManager.GetString("FirstTwoStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=4:(1);x=9,y=5:(1);x=9,y=6:(1);x=9,y=7:(1);x=9,y=9:(1);x=9,y=10:(1);x=9,y=12:(1);x=9,y=13:(1);x=9,y=17:(1);x=9,y=18:(1);x=9,y=19:(1);x=9,y=20:(1);x=9,y=21:(1);x=9,y=22:(1);x=10,y=24:(1);x=9,y=24:(1);x=9,y=23:(1);x=11,y=24:(1);x=12,y=24:(1);x=17,y=24:(1);x=18,y=24:(1);x=19,y=24:(1);x=20,y=24:(1);x=22,y=24:(1);x=23,y=24:(1);x=24,y=24:(1);x=26,y=24:(1);x=25,y=24:(1);x=27,y=24:(1);x=27,y=23:(1);x=27,y=17:(1);x=27,y=16:(1);x=27,y=14:(1);x=27,y=12:(1);x=27,y=11:(1);x=27,y=10:(1);x=27,y=9:(1);x=27,y=8: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GhostWalls {
            get {
                return ResourceManager.GetString("GhostWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=8:(7);x=9,y=9:(7);x=9,y=10:(7);x=9,y=11:(7);x=9,y=12:(7);x=9,y=13:(7);x=9,y=14:(7);x=9,y=15:(7);x=9,y=16:(7);x=9,y=17:(7);x=9,y=18:(7);x=9,y=19:(7);x=9,y=20:(7);x=9,y=22:(7);x=9,y=23:(7);x=9,y=24:(7);x=9,y=25:(7);x=9,y=21:(7);x=20,y=25:(7);x=20,y=24:(7);x=20,y=23:(7);x=20,y=15:(7);x=20,y=14:(7);x=20,y=9:(7);x=20,y=8:(7);x=9,y=7:(6);x=10,y=7:(6);x=11,y=7:(6);x=12,y=7:(6);x=13,y=7:(6);x=14,y=7:(6);x=15,y=7:(6);x=20,y=7:(6);x=21,y=7:(10);x=21,y=8:(10);x=21,y=9:(10);x=21,y=10:(10);x=21,y=11:(10);x= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GreenWalls {
            get {
                return ResourceManager.GetString("GreenWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HardStone {
            get {
                return ResourceManager.GetString("HardStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=10:(3);x=10,y=10:(3);x=11,y=10:(3);x=12,y=10:(3);x=13,y=10:(3);x=14,y=10:(3);x=15,y=10:(3);x=16,y=10:(3);x=17,y=10:(3);x=18,y=10:(3);x=18,y=11:(3);x=18,y=16:(3);x=18,y=17:(3);x=17,y=17:(3);x=16,y=17:(3);x=15,y=17:(3);x=14,y=17:(3);x=13,y=17:(3);x=12,y=17:(3);x=11,y=17:(3);x=10,y=17:(3);x=8,y=16:(3);x=8,y=17:(3);x=9,y=17:(3);x=8,y=11:(3);x=8,y=10:(3);x=9,y=11:(2);x=10,y=11:(2);x=11,y=11:(2);x=12,y=11:(2);x=13,y=11:(2);x=14,y=11:(2);x=15,y=11:(2);x=16,y=11:(2);x=17,y=11:(2);x=8,y=18:(2);x=9,y=18: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HowToButton {
            get {
                return ResourceManager.GetString("HowToButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=6,y=4:(9);x=6,y=5:(9);x=6,y=6:(9);x=6,y=9:(9);x=6,y=10:(9);x=6,y=11:(9);x=6,y=12:(9);x=6,y=13:(9);x=6,y=14:(9);x=6,y=15:(9);x=6,y=16:(9);x=6,y=17:(9);x=6,y=18:(9);x=6,y=19:(9);x=6,y=20:(9);x=6,y=21:(9);x=6,y=22:(9);x=7,y=22:(9);x=8,y=22:(9);x=9,y=22:(9);x=10,y=22:(9);x=11,y=22:(9);x=12,y=22:(9);x=13,y=22:(9);x=14,y=22:(9);x=15,y=22:(9);x=16,y=22:(9);x=17,y=22:(9);x=18,y=22:(9);x=19,y=22:(9);x=20,y=22:(9);x=21,y=22:(9);x=22,y=22:(9);x=23,y=22:(9);x=24,y=22:(9);x=25,y=22:(9);x=25,y=18:(9);x=25,y=17:( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvisibleMaze {
            get {
                return ResourceManager.GetString("InvisibleMaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=2,y=23:(3);x=2,y=22:(3);x=2,y=21:(3);x=2,y=20:(3);x=2,y=19:(3);x=2,y=18:(3);x=2,y=24:(3);x=3,y=24:(3);x=4,y=24:(3);x=5,y=24:(3);x=6,y=24:(3);x=7,y=24:(3);x=8,y=24:(3);x=9,y=24:(3);x=10,y=24:(3);x=11,y=24:(3);x=12,y=24:(3);x=13,y=24:(3);x=14,y=24:(3);x=15,y=24:(3);x=2,y=17:(3);x=3,y=17:(3);x=4,y=17:(3);x=5,y=17:(3);x=6,y=17:(3);x=7,y=17:(3);x=8,y=17:(3);x=9,y=17:(3);x=10,y=17:(3);x=11,y=17:(3);x=12,y=17:(3);x=13,y=17:(3);x=14,y=17:(3);x=15,y=17:(3);x=16,y=24:(3);x=17,y=24:(3);x=18,y=24:(3);x=19,y=24 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongFirstLevel {
            get {
                return ResourceManager.GetString("LongFirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=2,y=15:(3);x=16,y=25:(3);x=17,y=25:(3);x=18,y=25:(3);x=16,y=26:(2);x=17,y=26:(2);x=18,y=26:(2);x=19,y=26:(2);x=2,y=14:(3);x=2,y=13:(3);x=2,y=12:(3);x=2,y=11:(3);x=2,y=10:(3);x=2,y=9:(3);x=2,y=8:(3);x=2,y=3:(3);x=2,y=4:(3);x=2,y=5:(3);x=2,y=6:(3);x=2,y=7:(3);x=3,y=3:(3);x=4,y=3:(3);x=5,y=3:(3);x=6,y=3:(3);x=7,y=3:(3);x=8,y=3:(3);x=9,y=3:(3);x=10,y=3:(3);x=11,y=3:(3);x=12,y=3:(3);x=13,y=3:(3);x=14,y=3:(3);x=15,y=3:(3);x=17,y=3:(3);x=18,y=3:(3);x=19,y=3:(3);x=20,y=3:(3);x=21,y=3:(3);x=22,y=3:(3);x=23, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongGreenButtonFirst {
            get {
                return ResourceManager.GetString("LongGreenButtonFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=6,y=5:(1);x=6,y=6:(1);x=6,y=7:(1);x=6,y=10:(1);x=6,y=11:(1);x=6,y=12:(1);x=6,y=13:(1);x=6,y=14:(1);x=6,y=15:(1);x=6,y=16:(1);x=6,y=17:(1);x=6,y=18:(1);x=6,y=19:(1);x=6,y=20:(1);x=6,y=21:(1);x=6,y=22:(1);x=6,y=23:(1);x=25,y=23:(1);x=25,y=21:(1);x=25,y=19:(1);x=25,y=18:(1);x=25,y=17:(1);x=24,y=14:(1);x=24,y=13:(1);x=25,y=13:(1);x=25,y=9:(1);x=25,y=8:(1);x=25,y=7:(1);x=25,y=6:(1);x=25,y=5:(1);x=21,y=5:(1);x=20,y=5:(1);x=18,y=5:(1);x=17,y=5:(1);x=14,y=5:(1);x=9,y=5:(1);x=8,y=5:(1);x=7,y=5:(1);x=25,y=14 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MazeRunner {
            get {
                return ResourceManager.GetString("MazeRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=10,y=20:(3);x=10,y=19:(3);x=10,y=18:(3);x=10,y=17:(3);x=10,y=16:(3);x=10,y=15:(3);x=10,y=14:(3);x=10,y=13:(3);x=10,y=12:(3);x=11,y=12:(3);x=12,y=12:(3);x=13,y=12:(3);x=14,y=12:(3);x=15,y=12:(3);x=16,y=12:(3);x=17,y=12:(3);x=18,y=12:(3);x=19,y=12:(3);x=20,y=12:(3);x=21,y=12:(3);x=11,y=20:(3);x=12,y=20:(3);x=13,y=20:(3);x=14,y=20:(3);x=17,y=20:(3);x=18,y=20:(3);x=21,y=20:(3);x=23,y=20:(3);x=22,y=20:(3);x=20,y=20:(3);x=19,y=20:(3);x=15,y=20:(3);x=16,y=20:(3);x=24,y=20:(3);x=24,y=19:(3);x=24,y=18:(3);x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewYellowPlate {
            get {
                return ResourceManager.GetString("NewYellowPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=13,y=18:(3);x=12,y=18:(3);x=12,y=19:(3);x=12,y=20:(3);x=12,y=21:(3);x=12,y=22:(3);x=16,y=22:(3);x=15,y=18:(3);x=16,y=18:(3);x=16,y=19:(3);x=16,y=20:(3);x=16,y=21:(3);x=12,y=15:(3);x=13,y=15:(3);x=14,y=15:(3);x=15,y=15:(3);x=16,y=15:(3);x=12,y=23:(3);x=13,y=23:(3);x=14,y=23:(3);x=15,y=23:(3);x=16,y=23:(3);x=13,y=19:(2);x=15,y=19:(2);x=12,y=24:(2);x=13,y=24:(2);x=14,y=24:(2);x=15,y=24:(2);x=16,y=24:(2);x=12,y=16:(2);x=13,y=16:(2);x=14,y=16:(2);x=15,y=16:(2);x=16,y=16:(2);x=12,y=17:(1);x=13,y=17:(1);x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoBack {
            get {
                return ResourceManager.GetString("NoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=6,y=11:(3);x=6,y=12:(3);x=6,y=13:(3);x=6,y=14:(3);x=7,y=11:(3);x=8,y=11:(3);x=9,y=11:(3);x=10,y=11:(3);x=11,y=11:(3);x=13,y=11:(3);x=14,y=11:(3);x=6,y=15:(3);x=6,y=16:(3);x=6,y=17:(3);x=6,y=18:(3);x=7,y=18:(3);x=8,y=18:(3);x=9,y=18:(3);x=10,y=18:(3);x=11,y=18:(3);x=12,y=18:(3);x=13,y=18:(3);x=14,y=18:(3);x=15,y=18:(3);x=16,y=18:(3);x=17,y=18:(3);x=15,y=11:(3);x=16,y=11:(3);x=17,y=11:(3);x=7,y=12:(2);x=8,y=12:(2);x=9,y=12:(2);x=10,y=12:(2);x=11,y=12:(2);x=12,y=12:(2);x=13,y=12:(2);x=14,y=12:(2);x=15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlateCastle {
            get {
                return ResourceManager.GetString("PlateCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=8,y=20:(3);x=9,y=20:(3);x=10,y=20:(3);x=11,y=20:(3);x=12,y=20:(3);x=13,y=20:(3);x=14,y=20:(3);x=15,y=20:(3);x=8,y=19:(3);x=8,y=18:(3);x=8,y=17:(3);x=8,y=16:(3);x=8,y=15:(3);x=8,y=14:(3);x=9,y=14:(3);x=10,y=14:(3);x=11,y=14:(3);x=12,y=14:(3);x=13,y=14:(3);x=14,y=14:(3);x=15,y=14:(3);x=16,y=14:(3);x=17,y=14:(3);x=18,y=14:(3);x=19,y=14:(3);x=19,y=15:(3);x=19,y=16:(3);x=19,y=17:(3);x=19,y=18:(3);x=19,y=19:(3);x=19,y=20:(3);x=18,y=20:(3);x=17,y=20:(3);x=16,y=20:(3);x=9,y=15:(2);x=10,y=15:(2);x=11,y=15:( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomPlates {
            get {
                return ResourceManager.GetString("RandomPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=8,y=9:(3);x=8,y=10:(3);x=8,y=12:(3);x=8,y=13:(3);x=8,y=14:(3);x=8,y=15:(3);x=9,y=9:(3);x=10,y=9:(3);x=11,y=9:(3);x=12,y=9:(3);x=13,y=9:(3);x=14,y=9:(3);x=15,y=9:(3);x=16,y=9:(3);x=17,y=9:(3);x=18,y=9:(3);x=19,y=9:(3);x=20,y=9:(3);x=21,y=15:(3);x=21,y=14:(3);x=21,y=13:(3);x=21,y=12:(3);x=21,y=11:(3);x=21,y=10:(3);x=21,y=9:(3);x=9,y=10:(2);x=10,y=10:(2);x=11,y=10:(2);x=12,y=10:(2);x=13,y=10:(2);x=14,y=10:(2);x=15,y=10:(2);x=16,y=10:(2);x=17,y=10:(2);x=18,y=10:(2);x=19,y=10:(2);x=20,y=10:(2);x=8,y=17: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RightStoneWay {
            get {
                return ResourceManager.GetString("RightStoneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=7,y=11:(3);x=9,y=16:(3);x=10,y=16:(3);x=11,y=16:(3);x=12,y=16:(3);x=13,y=16:(3);x=14,y=16:(3);x=15,y=16:(3);x=16,y=16:(3);x=17,y=16:(3);x=18,y=16:(3);x=19,y=16:(3);x=20,y=16:(3);x=21,y=16:(3);x=22,y=16:(3);x=23,y=16:(3);x=8,y=11:(3);x=17,y=11:(3);x=19,y=11:(3);x=20,y=11:(3);x=21,y=11:(3);x=22,y=11:(3);x=23,y=11:(3);x=18,y=11:(3);x=16,y=11:(3);x=15,y=11:(3);x=14,y=11:(3);x=13,y=11:(3);x=12,y=11:(3);x=11,y=11:(3);x=10,y=11:(3);x=9,y=11:(3);x=6,y=11:(3);x=5,y=11:(3);x=4,y=11:(3);x=3,y=11:(3);x=2,y=11: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RollingStones {
            get {
                return ResourceManager.GetString("RollingStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=7,y=9:(3);x=7,y=10:(3);x=7,y=11:(3);x=7,y=12:(3);x=7,y=13:(3);x=8,y=9:(3);x=9,y=9:(3);x=10,y=9:(3);x=11,y=9:(3);x=12,y=9:(3);x=13,y=9:(3);x=7,y=14:(3);x=7,y=15:(3);x=8,y=15:(3);x=9,y=15:(3);x=10,y=15:(3);x=11,y=15:(3);x=12,y=15:(3);x=13,y=15:(3);x=14,y=9:(3);x=15,y=9:(3);x=16,y=9:(3);x=17,y=9:(3);x=17,y=10:(3);x=17,y=11:(3);x=17,y=12:(3);x=17,y=13:(3);x=17,y=14:(3);x=17,y=15:(3);x=16,y=15:(3);x=15,y=15:(3);x=14,y=15:(3);x=8,y=10:(2);x=9,y=10:(2);x=10,y=10:(2);x=11,y=10:(2);x=12,y=10:(2);x=13,y=10:( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmallPLateLevel {
            get {
                return ResourceManager.GetString("SmallPLateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=7,y=26:(3);x=7,y=27:(3);x=7,y=28:(3);x=15,y=28:(3);x=15,y=27:(3);x=15,y=26:(3);x=15,y=25:(3);x=15,y=24:(3);x=15,y=23:(3);x=15,y=22:(3);x=15,y=21:(3);x=15,y=20:(3);x=15,y=19:(3);x=15,y=18:(3);x=15,y=17:(3);x=11,y=19:(3);x=11,y=18:(3);x=11,y=17:(3);x=11,y=16:(3);x=11,y=15:(3);x=11,y=14:(3);x=15,y=16:(3);x=15,y=15:(3);x=15,y=14:(3);x=14,y=14:(3);x=12,y=14:(3);x=13,y=14:(3);x=12,y=15:(2);x=13,y=15:(2);x=14,y=15:(2);x=7,y=29:(3);x=9,y=29:(3);x=10,y=29:(3);x=11,y=29:(3);x=12,y=29:(3);x=13,y=29:(3);x=14,y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StartLevel {
            get {
                return ResourceManager.GetString("StartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=8,y=17:(4);x=7,y=17:(4);x=6,y=17:(4);x=9,y=18:(4);x=8,y=18:(4);x=7,y=18:(4);x=6,y=18:(4);x=10,y=18:(4);x=10,y=17:(4);x=10,y=16:(4);x=11,y=17:(4);x=11,y=16:(4);x=5,y=18:(4);x=5,y=17:(4);x=5,y=16:(4);x=4,y=18:(4);x=4,y=17:(4);x=4,y=16:(4);x=5,y=11:(4);x=4,y=11:(4);x=4,y=10:(4);x=5,y=10:(4);x=6,y=10:(4);x=6,y=11:(4);x=8,y=11:(4);x=7,y=10:(4);x=8,y=10:(4);x=9,y=10:(4);x=10,y=10:(4);x=10,y=11:(4);x=11,y=10:(4);x=11,y=11:(4);x=7,y=11:(4);x=6,y=16:(4);x=7,y=16:(4);x=9,y=11:(4);x=8,y=16:(4);x=9,y=17:(4);x= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoneGarden {
            get {
                return ResourceManager.GetString("StoneGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=7,y=20:(3);x=8,y=20:(3);x=9,y=20:(3);x=10,y=20:(3);x=11,y=20:(3);x=12,y=20:(3);x=13,y=20:(3);x=14,y=20:(3);x=15,y=20:(3);x=16,y=20:(3);x=19,y=20:(3);x=20,y=20:(3);x=20,y=14:(3);x=20,y=13:(3);x=20,y=12:(3);x=19,y=12:(3);x=18,y=12:(3);x=17,y=12:(3);x=16,y=12:(3);x=15,y=12:(3);x=14,y=12:(3);x=12,y=12:(3);x=11,y=12:(3);x=10,y=12:(3);x=9,y=12:(3);x=8,y=12:(3);x=7,y=12:(3);x=6,y=12:(3);x=6,y=13:(3);x=6,y=14:(3);x=6,y=15:(3);x=6,y=16:(3);x=6,y=17:(3);x=6,y=18:(3);x=6,y=19:(3);x=6,y=20:(3);x=16,y=11:(3);x= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoneLevel {
            get {
                return ResourceManager.GetString("StoneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=7:(3);x=9,y=8:(3);x=9,y=9:(3);x=9,y=10:(3);x=9,y=11:(3);x=9,y=12:(3);x=9,y=13:(3);x=9,y=14:(3);x=9,y=15:(3);x=9,y=16:(3);x=9,y=17:(3);x=9,y=18:(3);x=9,y=19:(3);x=10,y=7:(3);x=11,y=7:(3);x=13,y=7:(3);x=14,y=7:(3);x=15,y=7:(3);x=12,y=7:(3);x=10,y=19:(3);x=11,y=19:(3);x=12,y=19:(3);x=13,y=19:(3);x=14,y=19:(3);x=15,y=13:(3);x=15,y=15:(3);x=15,y=16:(3);x=15,y=17:(3);x=15,y=18:(3);x=15,y=19:(3);x=15,y=12:(3);x=15,y=11:(3);x=15,y=10:(3);x=15,y=9:(3);x=15,y=8:(3);x=14,y=8:(2);x=13,y=8:(2);x=12,y=8:(2); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoneWalls {
            get {
                return ResourceManager.GetString("StoneWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Textures {
            get {
                object obj = ResourceManager.GetObject("Textures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=8,y=27:(3);x=8,y=26:(3);x=8,y=25:(3);x=8,y=24:(3);x=8,y=23:(3);x=8,y=22:(3);x=8,y=21:(3);x=8,y=20:(3);x=8,y=19:(3);x=8,y=18:(3);x=9,y=18:(3);x=10,y=18:(3);x=11,y=18:(3);x=12,y=18:(3);x=13,y=18:(3);x=14,y=18:(3);x=15,y=18:(3);x=16,y=18:(3);x=17,y=18:(3);x=18,y=18:(3);x=19,y=18:(3);x=9,y=27:(3);x=10,y=27:(3);x=11,y=27:(3);x=12,y=27:(3);x=15,y=27:(3);x=16,y=27:(3);x=17,y=27:(3);x=18,y=27:(3);x=14,y=27:(3);x=19,y=27:(3);x=19,y=26:(3);x=19,y=25:(3);x=19,y=24:(3);x=19,y=23:(3);x=19,y=22:(3);x=19,y=21:(3) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriplePlatesStone {
            get {
                return ResourceManager.GetString("TriplePlatesStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer0&gt;x=9,y=11:(1);x=9,y=12:(1);x=9,y=13:(1);x=9,y=14:(1);x=9,y=16:(1);x=9,y=17:(1);x=9,y=19:(1);x=9,y=20:(1);x=9,y=21:(1);x=10,y=21:(1);x=11,y=21:(1);x=12,y=21:(1);x=13,y=21:(1);x=14,y=21:(1);x=16,y=21:(1);x=19,y=21:(1);x=20,y=21:(1);x=21,y=21:(1);x=22,y=21:(1);x=23,y=21:(1);x=23,y=18:(1);x=23,y=17:(1);x=23,y=16:(1);x=23,y=12:(1);x=23,y=11:(1);x=23,y=10:(1);x=23,y=9:(1);x=23,y=7:(1);x=23,y=6:(1);x=22,y=5:(1);x=21,y=5:(1);x=20,y=5:(1);x=19,y=5:(1);x=16,y=5:(1);x=15,y=5:(1);x=14,y=5:(1);x=10,y=6:(1);x=9,y=9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoStones {
            get {
                return ResourceManager.GetString("TwoStones", resourceCulture);
            }
        }
    }
}
